import type { Metadata } from 'next';
import Link from 'next/link';
import { Flame, ArrowLeft, FileText } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service — PokketFit',
  description:
    'Read the PokketFit Terms of Service. Understand your rights and responsibilities when using our fitness coaching platform.',
};

export default function TermsOfServicePage() {
  const lastUpdated = 'September 2026';

  return (
    <div className="min-h-[100dvh] bg-[#0A0705] text-[#FAF8F5] font-sans">
      {/* Header */}
      <header className="sticky top-0 z-40 bg-[#0A0705]/90 backdrop-blur-xl border-b border-white/[0.07] px-4 sm:px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center space-x-2 group">
            <div className="w-8 h-8 rounded-xl bg-[#E37210] flex items-center justify-center">
              <Flame className="w-4 h-4 text-white fill-white" />
            </div>
            <span className="font-extrabold text-base tracking-tight text-white">POKKETFIT</span>
          </Link>
          <Link
            href="/"
            className="flex items-center space-x-1.5 text-xs font-semibold text-[#8A8279] hover:text-white transition-colors"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Back to site</span>
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-12 sm:py-16 space-y-10">
        {/* Title block */}
        <div className="space-y-3">
          <div className="flex items-center space-x-2">
            <FileText className="w-5 h-5 text-[#E37210]" />
            <span className="text-xs font-bold text-[#E37210] uppercase tracking-widest">Legal</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight leading-tight">
            Terms of Service
          </h1>
          <p className="text-sm text-[#8A8279]">Last updated: {lastUpdated}</p>
        </div>

        <div className="bg-[#16120E] border border-[#2A241E] rounded-2xl p-5 text-sm text-[#A8A096] leading-relaxed">
          By creating a PokketFit account or using the PokketFit application, you agree to these
          Terms of Service. Please read them carefully. If you do not agree, do not use the
          service.
        </div>

        <LegalSection title="1. About PokketFit">
          <p>
            PokketFit is a personal wellness coaching tool that provides personalised workout plans,
            Nigerian-friendly nutrition guidance, hydration tracking, habit building tools, and
            progress monitoring features. It is operated as a web and Progressive Web Application
            (PWA).
          </p>
          <p>
            <strong>PokketFit is not a medical service.</strong> All content, recommendations, and
            plans generated by PokketFit are for informational and motivational purposes only and
            do not constitute clinical medical advice. Always consult a qualified healthcare
            professional before starting any new fitness or nutrition programme.
          </p>
        </LegalSection>

        <LegalSection title="2. Eligibility">
          <p>To use PokketFit, you must:</p>
          <ul>
            <li>Be at least 18 years of age.</li>
            <li>
              Have obtained appropriate medical clearance if you have a condition that may be
              affected by exercise (including but not limited to: pregnancy, postpartum recovery,
              cardiovascular conditions, musculoskeletal injuries).
            </li>
            <li>Provide accurate information during onboarding. Inaccurate data will result in unsuitable recommendations.</li>
          </ul>
        </LegalSection>

        <LegalSection title="3. Your Account">
          <p>
            You are responsible for maintaining the confidentiality of your account credentials.
            Do not share your password with anyone. You are responsible for all activity that
            occurs under your account.
          </p>
          <p>
            If you believe your account has been compromised, contact us immediately at{' '}
            <a href="mailto:support@pokketfit.app" className="text-[#E37210] underline">
              support@pokketfit.app
            </a>
            .
          </p>
        </LegalSection>

        <LegalSection title="4. Acceptable Use">
          <p>You agree not to:</p>
          <ul>
            <li>Use PokketFit for any unlawful purpose.</li>
            <li>Attempt to access other users&apos; data or accounts.</li>
            <li>Reverse-engineer, decompile, or extract source code from the application.</li>
            <li>
              Transmit any harmful, offensive, or misleading content through any part of the
              service.
            </li>
            <li>
              Use automated tools to scrape, crawl, or extract data from PokketFit without prior
              written consent.
            </li>
          </ul>
        </LegalSection>

        <LegalSection title="5. Health Disclaimer">
          <p>
            Exercise involves physical risk. By using PokketFit&apos;s workout plans, you
            acknowledge that:
          </p>
          <ul>
            <li>
              You are voluntarily participating in fitness activities and assume all associated
              risks.
            </li>
            <li>
              PokketFit is not liable for any injury, illness, or adverse health outcome resulting
              from following its recommendations.
            </li>
            <li>
              Postpartum users must confirm medical clearance before proceeding with postpartum
              fitness plans.
            </li>
            <li>
              BMI calculations and goal recommendations are based on WHO standard guidelines and
              are screening tools, not clinical diagnoses.
            </li>
          </ul>
        </LegalSection>

        <LegalSection title="6. Intellectual Property">
          <p>
            All content, design, code, and functionality within PokketFit — including workout
            plans, meal recommendations, branding, and UI — is the intellectual property of
            PokketFit. You may not reproduce, distribute, or create derivative works without
            written permission.
          </p>
          <p>
            You retain ownership of the personal data you provide (name, health metrics, logs).
            See our{' '}
            <Link href="/privacy" className="text-[#E37210] underline">
              Privacy Policy
            </Link>{' '}
            for details on how we handle it.
          </p>
        </LegalSection>

        <LegalSection title="7. Availability &amp; Changes">
          <p>
            PokketFit is provided on an &ldquo;as-is&rdquo; basis. We strive for high availability
            but do not guarantee uninterrupted service. We reserve the right to modify, suspend,
            or discontinue any feature at any time, with reasonable notice where possible.
          </p>
          <p>
            We may update these Terms periodically. Continued use of PokketFit after updates
            constitutes your acceptance of the revised Terms.
          </p>
        </LegalSection>

        <LegalSection title="8. Limitation of Liability">
          <p>
            To the maximum extent permitted by applicable law, PokketFit and its operators shall
            not be liable for any indirect, incidental, consequential, or punitive damages arising
            from your use of the service, including but not limited to physical injury, data loss,
            or service interruptions.
          </p>
        </LegalSection>

        <LegalSection title="9. Governing Law">
          <p>
            These Terms are governed by the laws of the Federal Republic of Nigeria. Any disputes
            shall be subject to the exclusive jurisdiction of Nigerian courts, without prejudice to
            applicable consumer protection rights in your jurisdiction.
          </p>
        </LegalSection>

        <LegalSection title="10. Contact Us">
          <p>For questions about these Terms, contact:</p>
          <p>
            <strong>PokketFit Legal</strong>
            <br />
            <a href="mailto:legal@pokketfit.app" className="text-[#E37210] underline">
              legal@pokketfit.app
            </a>
          </p>
        </LegalSection>
      </main>

      {/* Footer */}
      <footer className="border-t border-white/[0.06] py-8 px-4 sm:px-6">
        <div className="max-w-3xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-[#706760]">
          <span>© {new Date().getFullYear()} PokketFit. All rights reserved.</span>
          <div className="flex items-center space-x-4">
            <Link href="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link>
            <Link href="/terms" className="text-[#E37210]">Terms of Service</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

// ─── Reusable section component ───────────────────────────────────────────────

function LegalSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-lg font-bold text-white tracking-tight">{title}</h2>
      <div className="text-sm text-[#A8A096] leading-relaxed space-y-3 [&_ul]:space-y-2 [&_ul]:list-disc [&_ul]:pl-5 [&_strong]:text-[#C7BFB5] [&_a]:text-[#E37210]">
        {children}
      </div>
    </section>
  );
}
