import { Exercise, Workout, Meal, FruitItem } from '../types';

export const SEED_HOME_EXERCISES: Exercise[] = [
  // --- Lower Body ---
  {
    id: 'ex-chair-squats',
    name: 'Chair Squats',
    category: 'lower_body',
    environment: 'both',
    works: 'Quads, glutes, core',
    instruction: 'Sit toward a stable chair and stand without using hands where comfortable. Keep chest lifted.',
    safetyNote: 'Ensure the chair is flush against a wall so it cannot slide.',
    targetMuscles: ['Quadriceps', 'Gluteus Maximus', 'Core'],
    difficultyLevels: ['beginner', 'intermediate', 'expert'],
    fitnessTypes: ['underweight', 'normal_weight', 'overweight', 'postpartum'],
    equipmentRequired: ['Sturdy household chair'],
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSec: 60,
    status: 'published',
    mediaUrl: 'https://res.cloudinary.com/wknehnhq/video/upload/q_auto,f_auto,w_720/ex-chair-squats',
  },
  {
    id: 'ex-glute-bridges',
    name: 'Glute Bridges',
    category: 'lower_body',
    environment: 'both',
    works: 'Glutes, hamstrings',
    instruction: 'Lie on your back with knees bent, lift hips into the air, and firmly contract glutes at the top.',
    safetyNote: 'Avoid over-arching the lower back; pivot through your heels.',
    targetMuscles: ['Glutes', 'Hamstrings', 'Lower Back'],
    difficultyLevels: ['beginner', 'intermediate', 'expert'],
    fitnessTypes: ['underweight', 'normal_weight', 'overweight', 'postpartum'],
    equipmentRequired: ['Floor mat or carpet'],
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRestSec: 60,
    status: 'published',
    mediaUrl: 'https://res.cloudinary.com/wknehnhq/video/upload/q_auto,f_auto,w_720/ex-glute-bridges',
  },
  {
    id: 'ex-wall-sits',
    name: 'Wall Sits',
    category: 'lower_body',
    environment: 'both',
    works: 'Quads, muscular endurance',
    instruction: 'Slide your back against a smooth wall; lower to a comfortable seated angle and hold steadily.',
    safetyNote: 'Do not sink below 90 degrees if you have sensitive knee joints.',
    targetMuscles: ['Quadriceps', 'Calves'],
    difficultyLevels: ['beginner', 'intermediate', 'expert'],
    fitnessTypes: ['underweight', 'normal_weight', 'overweight'],
    equipmentRequired: ['Smooth wall space'],
    defaultSets: 3,
    defaultReps: '30-45 sec',
    defaultRestSec: 60,
    status: 'published',
  },
  {
    id: 'ex-reverse-lunges',
    name: 'Reverse Lunges',
    category: 'lower_body',
    environment: 'both',
    works: 'Quads, glutes, balance',
    instruction: 'Step backward with one leg and lower back knee in a smooth, controlled range of motion.',
    safetyNote: 'Keep front shin relatively vertical and maintain an upright torso.',
    targetMuscles: ['Quadriceps', 'Glutes', 'Stabilizers'],
    difficultyLevels: ['intermediate', 'expert'],
    fitnessTypes: ['normal_weight', 'overweight'],
    equipmentRequired: [],
    defaultSets: 3,
    defaultReps: '60 sec',
    defaultRestSec: 45,
    status: 'published',
    mediaUrl: 'https://res.cloudinary.com/wknehnhq/video/upload/q_auto,f_auto,w_720/ex-march-in-place',
  },
  {
    id: 'ex-calf-raises',
    name: 'Calf Raises',
    category: 'lower_body',
    environment: 'both',
    works: 'Calves, ankle stability',
    instruction: 'Hold a stable support or counter and rise onto toes with controlled tempo.',
    targetMuscles: ['Gastrocnemius', 'Soleus'],
    difficultyLevels: ['beginner', 'intermediate', 'expert'],
    fitnessTypes: ['underweight', 'normal_weight', 'overweight', 'postpartum'],
    equipmentRequired: ['Wall or counter for balance'],
    defaultSets: 3,
    defaultReps: '15-20',
    defaultRestSec: 45,
    status: 'published',
  },
  {
    id: 'ex-step-ups',
    name: 'Step-ups',
    category: 'lower_body',
    environment: 'both',
    works: 'Legs, conditioning',
    instruction: 'Use a sturdy low step or platform and step up with full foot placement and control.',
    safetyNote: 'Verify step stability before initiating.',
    targetMuscles: ['Quadriceps', 'Glutes'],
    difficultyLevels: ['beginner', 'intermediate'],
    fitnessTypes: ['normal_weight', 'overweight'],
    equipmentRequired: ['Low sturdy step'],
    defaultSets: 3,
    defaultReps: '10/leg',
    defaultRestSec: 60,
    status: 'published',
  },

  // --- Upper Body ---
  {
    id: 'ex-wall-pushups',
    name: 'Wall Push-ups',
    category: 'upper_body',
    environment: 'both',
    works: 'Chest, shoulders, triceps',
    instruction: 'Place palms on a wall at chest height; gently bend and extend arms with a straight core posture.',
    safetyNote: 'A gentle angle reduces joint pressure while building upper push mechanics.',
    targetMuscles: ['Pectorals', 'Anterior Deltoids', 'Triceps'],
    difficultyLevels: ['beginner', 'intermediate'],
    fitnessTypes: ['underweight', 'normal_weight', 'overweight', 'postpartum'],
    equipmentRequired: ['Wall'],
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSec: 60,
    status: 'published',
    mediaUrl: 'https://res.cloudinary.com/wknehnhq/video/upload/q_auto,f_auto,w_720/ex-wall-pushups',
  },
  {
    id: 'ex-incline-pushups',
    name: 'Incline Push-ups',
    category: 'upper_body',
    environment: 'both',
    works: 'Chest, triceps, core',
    instruction: 'Place hands on a stable elevated surface (counter or bench) and lower chest smoothly.',
    safetyNote: 'Keep elbows tucked at roughly 45 degrees to safeguard shoulders.',
    targetMuscles: ['Chest', 'Triceps', 'Core'],
    difficultyLevels: ['intermediate', 'expert'],
    fitnessTypes: ['underweight', 'normal_weight'],
    equipmentRequired: ['Stable bench or counter'],
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRestSec: 60,
    status: 'published',
  },
  {
    id: 'ex-chair-dips',
    name: 'Chair Dips',
    category: 'upper_body',
    environment: 'both',
    works: 'Triceps, shoulders',
    instruction: 'Using a heavy sturdy chair, place palms next to hips, lower gently, and press upward.',
    safetyNote: 'Keep back close to the chair edge and avoid sinking too low.',
    targetMuscles: ['Triceps', 'Front Shoulders'],
    difficultyLevels: ['intermediate', 'expert'],
    fitnessTypes: ['underweight', 'normal_weight'],
    equipmentRequired: ['Sturdy chair'],
    defaultSets: 3,
    defaultReps: '8-10',
    defaultRestSec: 60,
    status: 'published',
  },
  {
    id: 'ex-backpack-rows',
    name: 'Backpack Rows',
    category: 'upper_body',
    environment: 'both',
    works: 'Back, biceps, posture',
    instruction: 'Hinge forward with flat back and pull a safely weighted backpack towards your ribs.',
    safetyNote: 'Pack books or soft weights evenly so weight does not shift.',
    targetMuscles: ['Latissimus Dorsi', 'Rhomboids', 'Biceps'],
    difficultyLevels: ['beginner', 'intermediate', 'expert'],
    fitnessTypes: ['underweight', 'normal_weight', 'overweight'],
    equipmentRequired: ['Loaded backpack or water jug'],
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSec: 60,
    status: 'published',
  },
  {
    id: 'ex-shoulder-press',
    name: 'Shoulder Press',
    category: 'upper_body',
    environment: 'both',
    works: 'Shoulders, arms',
    instruction: 'Press approved light household items (or light dumbbells/bands) smoothly overhead without arching.',
    targetMuscles: ['Deltoids', 'Triceps'],
    difficultyLevels: ['beginner', 'intermediate', 'expert'],
    fitnessTypes: ['underweight', 'normal_weight', 'overweight', 'postpartum'],
    equipmentRequired: ['Two water bottles or light dumbbells'],
    defaultSets: 3,
    defaultReps: '12',
    defaultRestSec: 60,
    status: 'published',
  },
  {
    id: 'ex-plank-shoulder-taps',
    name: 'Plank Shoulder Taps',
    category: 'upper_body',
    environment: 'both',
    works: 'Shoulders, core, anti-rotation',
    instruction: 'From a stable high plank or knee plank, tap opposite shoulder without rocking your hips.',
    targetMuscles: ['Core', 'Deltoids', 'Glutes'],
    difficultyLevels: ['intermediate', 'expert'],
    fitnessTypes: ['normal_weight'],
    equipmentRequired: ['Mat'],
    defaultSets: 3,
    defaultReps: '10/side',
    defaultRestSec: 60,
    status: 'published',
  },

  // --- Core + Mobility ---
  {
    id: 'ex-dead-bug',
    name: 'Dead Bug',
    category: 'core_mobility',
    environment: 'both',
    works: 'Deep core, stability',
    instruction: 'Lie on your back, knees in tabletop; slowly lower opposite arm and leg while keeping back flat.',
    safetyNote: 'Press your navel gently toward spine to protect lumbar area.',
    targetMuscles: ['Transverse Abdominis', 'Pelvic Floor'],
    difficultyLevels: ['beginner', 'intermediate', 'expert'],
    fitnessTypes: ['underweight', 'normal_weight', 'overweight', 'postpartum'],
    equipmentRequired: ['Mat'],
    defaultSets: 3,
    defaultReps: '8-10/side',
    defaultRestSec: 45,
    status: 'published',
    mediaUrl: 'https://res.cloudinary.com/wknehnhq/video/upload/q_auto,f_auto,w_720/ex-dead-bug',
  },
  {
    id: 'ex-bird-dog',
    name: 'Bird Dog',
    category: 'core_mobility',
    environment: 'both',
    works: 'Core, back, balance',
    instruction: 'From quadruped position, extend opposite arm and leg parallel to floor. Hold 2 seconds.',
    targetMuscles: ['Erector Spinae', 'Gluteus', 'Core'],
    difficultyLevels: ['beginner', 'intermediate', 'expert'],
    fitnessTypes: ['underweight', 'normal_weight', 'overweight', 'postpartum'],
    equipmentRequired: ['Mat'],
    defaultSets: 3,
    defaultReps: '10/side',
    defaultRestSec: 45,
    status: 'published',
    mediaUrl: 'https://res.cloudinary.com/wknehnhq/video/upload/q_auto,f_auto,w_720/ex-bird-dog',
  },
  {
    id: 'ex-cat-cow',
    name: 'Cat-Cow Stretch',
    category: 'core_mobility',
    environment: 'both',
    works: 'Spine mobility, breath sync',
    instruction: 'Alternate between gentle rounding (cat) and natural extension (cow) with calm breaths.',
    targetMuscles: ['Spinal extensors', 'Neck', 'Thoracic spine'],
    difficultyLevels: ['beginner', 'intermediate', 'expert'],
    fitnessTypes: ['underweight', 'normal_weight', 'overweight', 'postpartum'],
    equipmentRequired: ['Mat'],
    defaultSets: 2,
    defaultReps: '10 cycles',
    defaultRestSec: 30,
    status: 'published',
  },
  {
    id: 'ex-hip-flexor-stretch',
    name: 'Hip Flexor Stretch',
    category: 'core_mobility',
    environment: 'both',
    works: 'Hip mobility, postural release',
    instruction: 'Take a supported half-kneeling position; gently tuck pelvis and lean forward slightly.',
    targetMuscles: ['Iliopsoas', 'Rectus Femoris'],
    difficultyLevels: ['beginner', 'intermediate', 'expert'],
    fitnessTypes: ['underweight', 'normal_weight', 'overweight', 'postpartum'],
    equipmentRequired: ['Cushion for knee'],
    defaultSets: 2,
    defaultReps: '30 sec/side',
    defaultRestSec: 30,
    status: 'published',
  },

  // --- Low Impact Cardio ---
  {
    id: 'ex-march-in-place',
    name: 'March in Place',
    category: 'low_impact_cardio',
    environment: 'both',
    works: 'Cardio, legs, coordination',
    instruction: 'March rhythmically while swinging arms naturally. Lift knees to a comfortable height.',
    targetMuscles: ['Hip Flexors', 'Calves', 'Cardiovascular System'],
    difficultyLevels: ['beginner', 'intermediate'],
    fitnessTypes: ['underweight', 'normal_weight', 'overweight', 'postpartum'],
    equipmentRequired: [],
    defaultSets: 3,
    defaultReps: '60 sec',
    defaultRestSec: 45,
    status: 'published',
  },
  {
    id: 'ex-step-touch',
    name: 'Step Touch + Arm Swings',
    category: 'low_impact_cardio',
    environment: 'both',
    works: 'Cardio, coordination',
    instruction: 'Step side to side with smooth arm swings, maintaining an energetic rhythm without heavy impact.',
    targetMuscles: ['Cardiovascular System', 'Adductors', 'Deltoids'],
    difficultyLevels: ['beginner', 'intermediate'],
    fitnessTypes: ['underweight', 'normal_weight', 'overweight', 'postpartum'],
    equipmentRequired: [],
    defaultSets: 3,
    defaultReps: '60 sec',
    defaultRestSec: 45,
    status: 'published',
  },
  {
    id: 'ex-shadow-boxing',
    name: 'Shadow Boxing',
    category: 'low_impact_cardio',
    environment: 'both',
    works: 'Cardio, shoulders, core',
    instruction: 'Deliver controlled, rhythmic punches (jabs, crosses) with light bouncing feet.',
    targetMuscles: ['Deltoids', 'Rotational Core', 'Aerobic Engine'],
    difficultyLevels: ['beginner', 'intermediate', 'expert'],
    fitnessTypes: ['normal_weight', 'overweight'],
    equipmentRequired: [],
    defaultSets: 3,
    defaultReps: '45 sec',
    defaultRestSec: 45,
    status: 'published',
  },

  // --- Full Body / Compound ---
  {
    id: 'ex-good-mornings',
    name: 'Bodyweight Good Mornings',
    category: 'full_body_compound',
    environment: 'both',
    works: 'Hamstrings, glutes, back',
    instruction: 'Hands behind head or crossed on chest, hinge at hips with soft knees and a neutral back.',
    targetMuscles: ['Hamstrings', 'Glutes', 'Erector Spinae'],
    difficultyLevels: ['beginner', 'intermediate', 'expert'],
    fitnessTypes: ['underweight', 'normal_weight', 'overweight', 'postpartum'],
    equipmentRequired: [],
    defaultSets: 3,
    defaultReps: '12',
    defaultRestSec: 45,
    status: 'published',
  },
  {
    id: 'ex-squat-to-press',
    name: 'Squat to Press',
    category: 'full_body_compound',
    environment: 'both',
    works: 'Legs, shoulders, core',
    instruction: 'Squat downward, then drive upward through heels directly into an overhead press.',
    targetMuscles: ['Quads', 'Glutes', 'Deltoids'],
    difficultyLevels: ['intermediate', 'expert'],
    fitnessTypes: ['normal_weight'],
    equipmentRequired: ['Light weights or water bottles'],
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSec: 60,
    status: 'published',
  },
  {
    id: 'ex-plank',
    name: 'Plank',
    category: 'full_body_compound',
    environment: 'both',
    works: 'Core, shoulders, endurance',
    instruction: 'Hold a firm straight-line plank from elbows or hands. Modify on knees when necessary.',
    targetMuscles: ['Core', 'Shoulders', 'Quads'],
    difficultyLevels: ['beginner', 'intermediate', 'expert'],
    fitnessTypes: ['normal_weight', 'underweight'],
    equipmentRequired: ['Mat'],
    defaultSets: 3,
    defaultReps: '30-45 sec',
    defaultRestSec: 60,
    status: 'published',
  },
];

export const SEED_MEALS: Meal[] = [
  {
    id: 'meal-oatmeal-chia',
    name: 'Nigerian Rolled Oatmeal with Chia & Banana',
    type: 'breakfast',
    description: 'Warm cooked oats topped with sliced sweet banana, soaked chia seeds, and a touch of local cinnamon.',
    portion: '1 medium bowl (approx 350g)',
    caloriesEst: 340,
    proteinGrams: 11,
    carbsGrams: 58,
    fatGrams: 6,
    fiberGrams: 8,
    isNigerianLocal: true,
    ingredients: ['Rolled oats', 'Chia seeds', 'Banana', 'Low-fat milk/water', 'Cinnamon'],
    allergens: ['Dairy (optional)'],
    approvedAlternatives: ['Millet Pap (Akamu) with boiled eggs', 'Moi-Moi with steamed fish'],
    status: 'published',
  },
  {
    id: 'meal-moimoi-egg',
    name: 'Protein Steamed Moi-Moi with Hard Boiled Egg',
    type: 'breakfast',
    description: 'Traditional Nigerian steamed bean pudding seasoned with sweet peppers, onions, and boiled egg.',
    portion: '2 wraps / 2 ramekins (approx 300g)',
    caloriesEst: 380,
    proteinGrams: 24,
    carbsGrams: 42,
    fatGrams: 10,
    fiberGrams: 9,
    isNigerianLocal: true,
    ingredients: ['Black-eyed beans', 'Bell peppers (Tatashe)', 'Onions', 'Boiled eggs', 'Olive or vegetable oil'],
    allergens: ['Eggs'],
    approvedAlternatives: ['Egg omelette with steamed plantain'],
    status: 'published',
  },
  {
    id: 'meal-grilled-chicken-brownrice',
    name: 'Suya-Spiced Grilled Chicken Breast & Brown Rice',
    type: 'lunch',
    description: 'Tender chicken breast coated in mild authentic Suya aromatics served with fragrant brown rice and steamed greens.',
    portion: '150g grilled breast, 1 cup cooked brown rice, 1 cup steamed spinach',
    caloriesEst: 510,
    proteinGrams: 44,
    carbsGrams: 54,
    fatGrams: 11,
    fiberGrams: 6,
    isNigerianLocal: true,
    ingredients: ['Chicken breast', 'Brown rice', 'Suya spice (mild)', 'Efo Shoko or spinach', 'Olive oil'],
    allergens: ['Peanut derivatives in suya spice (optional substitute: ginger-garlic rub)'],
    approvedAlternatives: ['Grilled Tilapia fillet with roasted plantains'],
    status: 'published',
  },
  {
    id: 'meal-jollof-fish-veg',
    name: 'Fit Smokey Jollof Rice with Grilled Tilapia & Efo',
    type: 'lunch',
    description: 'Portion-controlled party Jollof cooked in a rich tomato-pepper reduction, paired with grilled fresh tilapia.',
    portion: '1.2 cups Jollof rice, 1 medium Tilapia fillet, side garden salad',
    caloriesEst: 540,
    proteinGrams: 38,
    carbsGrams: 64,
    fatGrams: 12,
    fiberGrams: 5,
    isNigerianLocal: true,
    ingredients: ['Parboiled long grain rice', 'Tomatoes & Tatashe', 'Tilapia fillet', 'Onions', 'Garden greens'],
    allergens: ['Fish'],
    approvedAlternatives: ['Sweet potato mash with roasted chicken'],
    status: 'published',
  },
  {
    id: 'meal-eforiro-leanmeat',
    name: 'Rich Vegetable Soup (Efo Riro) with Lean Beef & Plantain',
    type: 'dinner',
    description: 'Leafy Nigerian spinach stew simmered with peppers, dried mushrooms, and lean tender beef steak strips.',
    portion: '1 bowl vegetable stew, 120g lean beef, 1 boiled unripe plantain',
    caloriesEst: 460,
    proteinGrams: 36,
    carbsGrams: 44,
    fatGrams: 14,
    fiberGrams: 8,
    isNigerianLocal: true,
    ingredients: ['Efo Tete/Spinach', 'Lean beef cuts', 'Tomatoes & peppers', 'Locust beans (Iru)', 'Unripe plantain'],
    allergens: [],
    approvedAlternatives: ['Okra soup with fresh sea bass & small oatmeal swallow'],
    status: 'published',
  },
  {
    id: 'meal-okra-fish',
    name: 'Fresh Okra & Seafood Medley with Small Poundo-Oat',
    type: 'dinner',
    description: 'Nutrient-rich lightly tossed okra soup with fresh prawns and white fish, paired with a small fiber-dense oat swallow.',
    portion: 'Generous bowl soup, 100g oat swallow ball',
    caloriesEst: 410,
    proteinGrams: 34,
    carbsGrams: 40,
    fatGrams: 9,
    fiberGrams: 7,
    isNigerianLocal: true,
    ingredients: ['Fresh sliced okra', 'Tiger prawns', 'Hake / White fish', 'Oatmeal flour', 'Scotch bonnet'],
    allergens: ['Crustaceans / Shellfish'],
    approvedAlternatives: ['Grilled chicken salad with avocado'],
    status: 'published',
  },
];

export const SEED_FRUITS: FruitItem[] = [
  {
    id: 'fruit-papaya',
    name: 'Ripe Nigerian Papaya (Pawpaw)',
    servingSize: '1 medium cup cubed (150g)',
    caloriesEst: 62,
    benefits: 'High in papain digestive enzymes, Vitamin C, and gut-soothing hydration.',
    isLocallyAvailable: true,
  },
  {
    id: 'fruit-watermelon',
    name: 'Crisp Red Watermelon Slices',
    servingSize: '2 thick slices (250g)',
    caloriesEst: 75,
    benefits: 'Excellent source of natural electrolytes, lycopene, and 92% bioavailable water.',
    isLocallyAvailable: true,
  },
  {
    id: 'fruit-mango',
    name: 'Sweet Ogbomoso / Benue Mango',
    servingSize: '1 medium whole mango',
    caloriesEst: 95,
    benefits: 'Packed with immune-enhancing Vitamin A, carotenoids, and natural energizing sugars.',
    isLocallyAvailable: true,
  },
  {
    id: 'fruit-orange',
    name: 'Fresh Nigerian Sweet Orange',
    servingSize: '1 large fruit (eaten whole for pulp fiber)',
    caloriesEst: 68,
    benefits: 'Rich in bioflavonoids, dietary pectin fiber, and revitalizing Vitamin C.',
    isLocallyAvailable: true,
  },
  {
    id: 'fruit-guava',
    name: 'Fresh Pink/White Guava',
    servingSize: '2 medium guavas',
    caloriesEst: 74,
    benefits: 'One of the highest fiber-to-calorie fruits globally with anti-glycemic properties.',
    isLocallyAvailable: true,
  },
];

export const MOTIVATIONAL_PROMPTS = [
  'Good morning! Consistency over perfection wins every single time.',
  "Let's make today count. Your body will thank you by sundown.",
  'Another win in the books. Keep that momentum rolling!',
  "Yesterday didn't go as planned? Today is a brand new page. Step forward.",
  'Your consistency is compounding into lifelong vitality and strength.',
  'Hydration fuels your focus, performance, and recovery. Take a sip!',
  'Honor your body where it is today, then guide it one rep further.',
];
